Module2 task1
htmlacademy-ecmascript/871783-big-trip-13 pull request #4
Opened 2020-11-25 19:09 UTC by aquamarya

2020-11-26 19:35 UTC, dean992008 requested changes

2020-11-26 19:35 UTC, dean992008 commented on package.json
> +    "dayjs": "1.9.5",
Не нужно спешить с зависимостями их нужно устанавливать когда это нужно. 

Зависимости правильные, не исправляй просто на будушее задания.

2020-11-26 19:35 UTC, dean992008 commented on src/consts.js
> +let eventOffers = [
Массивы и обьекты правильнее обьвлять как `const`, они остануться мутабельными, но ссылка не будет перезаписываться. 

Также пореконмендую добавить в ESLint правило чтобы оно подсказывало где правильно использовать const
```
rules:
  prefer-const: error
```

2020-11-26 19:35 UTC, dean992008 commented on src/main.js
> +// console.log(events);
Не забывай удалять коментированый код. 

Для того чтобы проверерить что получилось лучше пользоваться пошаговой отладной: 
https://youtu.be/eaQi6SblFQc

2020-11-26 19:35 UTC, dean992008 commented on src/utils.js
> +  return array[randomIndex];
Здесь ошибка, функция randomIndex не вызывается. 

Я бы переделал ее просто на переменую,

2020-11-26 19:35 UTC, dean992008 commented on src/consts.js
> +export {
Експорт должен быть в конце: https://up.htmlacademy.ru/ecmascript/13/criteries#b14

2020-11-26 19:35 UTC, dean992008 commented on src/mock/event.js
> +  return {
Нет поля с дополнительными опцыями: http://joxi.ru/DmBD646uJlKZ8A

2020-11-26 19:35 UTC, dean992008 commented on src/mock/event.js
> +    description += eventPlaceDescriptions[i];
Здесь скорее всего можно восмотрльзоваться https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/slice

2020-11-26 19:35 UTC, dean992008 commented on src/mock/event.js
> +    cityPhotosLinks.push(`http://picsum.photos/248/152?r=${Math.random()}`);
Для заоплнения я бы воспотльзовался конструкцией типа: 
```
new Array(getRandomInteger(photosAmount.MIN, photosAmount.MAX)).fill(``).map(()=>`http://picsum.photos/248/152?r=${Math.random()})
```

2020-11-26 19:35 UTC, dean992008 commented on src/main.js
> +export const events = new Array(EVENT_AMOUNT).fill().map(generateTripEvent);
Лучше сделать функцию которая будет возвращять массив в данными, а не заполнеть их прязо здесь.

2020-11-26 19:35 UTC, dean992008 commented on src/main.js
> +for (let i = 1; i < EVENT_AMOUNT; i++) {
Для отрисовки точек нужно перебирать массив.

2020-11-26 19:35 UTC, dean992008 commented on src/view/edit-event.js
> +      eventTypeList.push(`
Тоже нужно воспользовать fill и map

2020-11-26 19:35 UTC, dean992008 commented on src/view/trip-event-item.js
> +  // const getOffer = () => {
Не забывай удалять коментированый код.

2020-11-27 16:18 UTC, aquamarya commented on src/consts.js
> +let eventOffers = [
ок

2020-11-27 16:29 UTC, aquamarya commented on src/utils.js
> +  return array[randomIndex];
переделала, заработало)

2020-11-27 20:23 UTC, aquamarya commented on src/view/trip-event-item.js
> +  // const getOffer = () => {
обычно удаляю, а тут сознательно оставляла, т.к. точно знаю, что это не последнее ревью этого задания

2020-11-28 18:25 UTC, dean992008 approved these changes

2020-11-28 18:25 UTC, dean992008 commented on src/main.js
> +const createEvents = (amount) => {
Эту функцию лучше перенести в модуль с моками.

2020-11-28 18:25 UTC, dean992008 commented on src/main.js
> +for (let i = 1; i < events.length; i++) {
Для перебора массива правильнее использовать forEach или for...of

2020-11-28 18:25 UTC, dean992008 commented
Написал еще 2 коментария, поправишь вместе со следующим заданием.

2020-11-28 18:26 UTC, merged